Models/ApplicationDBContext.cs
using Microsoft.EntityFrameworkCore;

#nullable disable
namespace core.Models;
public class ApplicationDBContext : DbContext
{
    public ApplicationDBContext(DbContextOptions<ApplicationDBContext> dbContextOptions)
    : base(dbContextOptions)
    { }

    public DbSet<User> Users { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<Profile> Profiles { get; set; }
}

Models/ErrorViewModel.cs
namespace core.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/LoginModel.cs
namespace core.Models;

public class LoginModel
{
    // [Required]
    public string Name { get; set; }

}

Models/Profile.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace core.Models;
public class Profile
{
    [Key]
    [Display(Name = "Profile Id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int id { get; set; }
    [Required]
    public string Name { get; set; }

    public string ContactNo { get; set; }

}

Models/ProfileViewModel .cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace core.Models;

public class ProfileViewModel
{
    public int id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string ContactNo { get; set; }
}

Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace core.Models;
public class Student
{

    [Key]
    [Display(Name = "Student ID")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int StudentId { get; set; }

    [Required]
    [Column(TypeName = "varchar(50)")]
    public string? StudentName { get; set; }

    public string? Year { get; set; }

}

Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace core.Models;
public class User
{
    [Key]
    [Display(Name = "User Id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int id { get; set; }
    [Required]
    public string Name { get; set; }

}

Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace core.Models;

public class UserViewModel
{
    public int id { get; set; }

    [Required]
    public string Name { get; set; }

    // [Required]
    // [Display(Name = "Contact No.")]
    // [EmailAddress(ErrorMessage = "Invalid email address")]
    // public string ContactNo { get; set; }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using core.Models;

namespace core.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProfileController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using core.Models;
using core.IRepository;

namespace core.Controllers;

public class ProfileController : Controller
{

    readonly IProfileRepository iProfileRepository;

    public ProfileController(IProfileRepository _iProfileRepository)
    {
        iProfileRepository = _iProfileRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Create()
    {
        return View();
    }
    public IActionResult List()
    {
        var profileList = iProfileRepository.getAll();
        return View(profileList);
    }

    public IActionResult Edit(int id)
    {
        var profile = iProfileRepository.get(id);
        return View(profile);
    }

    public IActionResult Delete(int id)
    {
        var profile = iProfileRepository.delete(id);
        return RedirectToAction("List");
    }


    [HttpPost]
    public IActionResult Create(ProfileViewModel ProfileViewModel)
    {
        if (ModelState.IsValid)
        {
            iProfileRepository.addOrUpdae(ProfileViewModel);
            return RedirectToAction("List");
        }
        else
            return View();
    }
}

Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using core.Models;

namespace core.Controllers;

public class UserController : Controller
{

    private readonly ApplicationDBContext dbContext;
    public UserController(ApplicationDBContext db)
    {
        dbContext = db;
    }
    public IActionResult Index()
    {

        var user = new UserViewModel { id = 1, Name = "jessie" };

        // var user = new UserViewModel(
        //     {
        //         new UserViewModel {
        //             id = 1,
        //             Name= "xxx"
        //         }
        //     }
        // )
        return View(user);
    }

    [HttpPost]
    public IActionResult Create(UserViewModel userViewModel)
    {
        Console.WriteLine("test");
        if (ModelState.IsValid)
        {
            // schoolContext.Teacher.Add(teacher);  
            // schoolContext.SaveChanges();  
            Console.WriteLine("test");
            return RedirectToAction("Index");
        }
        else
            return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-12">
        <div class="card card-chart">
            <!---->
            <div class="card-header text-left">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Welcome back .NET</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <div class="chartjs-size-monitor">
                        <div class="chartjs-size-monitor-expand">
                            <div class=""></div>
                        </div>
                        <div class="chartjs-size-monitor-shrink">
                            <div class=""></div>
                        </div>
                    </div><canvas id="big-line-chart" width="3170" height="440"
                        style="display: block; height: 220px; width: 1585px;" class="chartjs-render-monitor"></canvas>
                </div>
            </div>
            <!---->
            <!---->
        </div>
    </div>
</div>

Views/Shared/Sidebar.cshtml
<div data="green" class="sidebar">
    <div class="sidebar-wrapper text-left">
        <div class="logo"><a href="#" class="simple-text logo-normal text-left">
                Refresh Knowlegde
            </a></div>
        <ul class="nav">
            <li class="nav-item ">
                <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="tim-icons icon-bank"></i>
                    <p>Home</p>
                </a>

            </li>
            <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="Profile" asp-action="List">
                    <i class="tim-icons icon-image-02"></i>
                    <p>Profie</p>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="User" asp-action="Index">
                    <i class="tim-icons icon-image-02"></i>
                    <p>User</p>
                </a>
            </li>
        </ul>
    </div>
</div>

Views/Shared/TopNav.cshtml
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                Home Page
            </a>
        </div>
    </div>
</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - core</title>

    <link rel="stylesheet" href="~/scss/white-dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/nucleo-icon.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

</head>

<body>
    <div class="content">
        <div class="wrapper">
            @Html.Partial("Sidebar")
            <div class="main-panel">
                @Html.Partial("TopNav")
                <div class="content">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/User/Index.cshtml
@model UserViewModel
@{
  ViewData["Title"] = "User Page";
}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header text-left">
        <h5 class="title">User Profile</h5>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-5 pr-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Company (disabled)
              </label><input aria-describedby="addon-right addon-left" placeholder="Company" disabled="disabled"
                class="form-control"></div>
          </div>
          <div class="col-md-3 px-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Username
              </label><input aria-describedby="addon-right addon-left" placeholder="Username" class="form-control">
            </div>
          </div>
          <div class="col-md-4 pl-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Email address
              </label><input aria-describedby="addon-right addon-left" type="email" placeholder="mike@email.com"
                class="form-control"></div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 pr-md-1 text-left">
            <div class="form-group"><label class="control-label">
                First Name
              </label><input aria-describedby="addon-right addon-left" placeholder="First Name" class="form-control">
            </div>
          </div>
          <div class="col-md-6 pl-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Last Name
              </label><input aria-describedby="addon-right addon-left" placeholder="Last Name" class="form-control">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-left">
            <div class="form-group"><label class="control-label">
                Address
              </label><input aria-describedby="addon-right addon-left" placeholder="Home Address" class="form-control">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 pr-md-1 text-left">
            <div class="form-group"><label class="control-label">
                City
              </label><input aria-describedby="addon-right addon-left" placeholder="City" class="form-control"></div>
          </div>
          <div class="col-md-4 px-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Country
              </label><input aria-describedby="addon-right addon-left" placeholder="Country" class="form-control"></div>
          </div>
          <div class="col-md-4 pl-md-1 text-left">
            <div class="form-group"><label class="control-label">
                Postal Code
              </label><input aria-describedby="addon-right addon-left" placeholder="ZIP Code" class="form-control">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 text-left">
            <div class="form-group"><label>About Me</label><textarea rows="4" cols="80"
                placeholder="Here can be your description" class="form-control"></textarea></div>
          </div>
        </div>
      </div>
      <div class="card-footer text-right"><button type="button" class="btn btn-success" fill="">Save</button></div>
    </div>
  </div>

</div>